pipeline {
    agent {label 'agent'}
    // environment {
    // }
    stages {
        stage('build'){
            steps{
              // sh 'env | grep -i java'
              // sh 'pwd'
              // sh 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
              // sh 'echo $M2_HOME'
              // sh 'export M2_HOME=/opt/apache-maven-3.9.6'
              sh 'cd code/eos-cloud-config-api && ls -l'
              sh 'mvn clean verify'
              // withMaven (
              //   // mavenLocalRepo: 'code/eos-cloud-config-api'
              // ){
              //   sh "mvn clean verify"
              // }
            }
            
        }
    }
}